[project]
name = "swagger-validator-v2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pyyaml>=6.0.2",
    "typer>=0.15.4",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
