name: Lokus PR Validation

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**.yaml'
      - '**.yml'
      - '**.json'

env:
  # Customize these variables for your project
  SPEC_PATH: "api-spec.yaml"  # Path to your API specification
  CONFIG_PATH: ".forbidden_keys.yaml"  # Path to your Lokus configuration
  PYTHON_VERSION: "3.11"  # Python version to use

permissions:
  contents: read
  pull-requests: write  # Required for PR comments

jobs:
  lokus-pr-validation:
    name: PR API Security Review
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.8"
          enable-cache: true

      - name: Set up Python
        run: uv python install ${{ env.PYTHON_VERSION }}

      - name: Install Lokus
        run: |
          uv tool install lokus
          echo "$(uv tool bin-dir)" >> $GITHUB_PATH

      - name: Check for API specification changes
        id: check-changes
        run: |
          # Check if API spec files were changed in this PR
          if git diff --name-only origin/${{ github.base_ref }}..HEAD | grep -E '\.(yaml|yml|json)$'; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "✅ API specification changes detected"
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "ℹ️  No API specification changes detected"
          fi

      - name: Create default config if not exists
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          if [ ! -f "${{ env.CONFIG_PATH }}" ]; then
            echo "Creating default Lokus configuration..."
            cat > "${{ env.CONFIG_PATH }}" << 'EOF'
          forbidden_keys:
            - "apiKey"
            - "password"
            - "secretKey"
            - "token"
            - "secret"
          
          forbidden_key_patterns:
            - ".*_token$"
            - ".*_key$"
            - "^secret_.*"
            - "^api_.*_secret$"
          
          forbidden_keys_at_paths:
            - path: "info.contact.email"
              key: "email"
              reason: "Contact email should not be in API specification"
          
          allowed_exceptions: []
          EOF
            echo "✅ Created default configuration: ${{ env.CONFIG_PATH }}"
          fi

      - name: Run Lokus validation with JSON output
        if: steps.check-changes.outputs.changes == 'true'
        id: lokus-validation
        run: |
          echo "🔍 Running Lokus validation on ${{ env.SPEC_PATH }}"
          
          # Run Lokus and capture output
          if lokus --config "${{ env.CONFIG_PATH }}" --json "${{ env.SPEC_PATH }}" > lokus-results.json 2>&1; then
            echo "validation=success" >> $GITHUB_OUTPUT
            echo "✅ Validation passed"
          else
            echo "validation=failure" >> $GITHUB_OUTPUT
            echo "❌ Validation failed"
          fi
          
          # Store results for comment
          if [ -f lokus-results.json ]; then
            echo "results_file=lokus-results.json" >> $GITHUB_OUTPUT
          fi

      - name: Create PR comment - Success
        if: steps.check-changes.outputs.changes == 'true' && steps.lokus-validation.outputs.validation == 'success'
        uses: actions/github-script@v7
        with:
          script: |
            const comment = `## 🔒 Lokus API Security Validation - ✅ PASSED
            
            **Great news!** Your API specification has passed all security and LGPD compliance checks.
            
            ### What was checked:
            - 🔍 Forbidden keys and patterns
            - 🛡️ Security requirements (OWASP API Security Top 10)
            - 📋 LGPD compliance requirements
            - 🔒 Sensitive data exposure
            
            ### Next steps:
            - Your API specification is ready for review
            - No security issues found
            - LGPD compliance requirements met
            
            ---
            *This check was performed by [Lokus](https://github.com/geavenx/lokus) - API Security & LGPD Compliance Validator*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: Create PR comment - Failure
        if: steps.check-changes.outputs.changes == 'true' && steps.lokus-validation.outputs.validation == 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let issuesText = "No specific issues found in JSON output.";
            
            try {
              if (fs.existsSync('lokus-results.json')) {
                const results = JSON.parse(fs.readFileSync('lokus-results.json', 'utf8'));
                if (results.findings && results.findings.length > 0) {
                  issuesText = results.findings.map((finding, index) => 
                    `${index + 1}. **${finding.type}** at \`${finding.path}\`: ${finding.message}`
                  ).join('\n');
                }
              }
            } catch (error) {
              console.log('Error reading JSON results:', error);
              issuesText = "Could not parse validation results. Please check the workflow logs.";
            }
            
            const comment = `## 🔒 Lokus API Security Validation - ❌ FAILED
            
            **Security and compliance issues found in your API specification.**
            
            ### Issues found:
            ${issuesText}
            
            ### What you need to do:
            1. 🔧 Fix the issues listed above
            2. 📝 Update your API specification
            3. 🔄 Push your changes to re-run validation
            
            ### Common solutions:
            - Remove forbidden keys from your API specification
            - Add proper security requirements to your endpoints
            - Ensure LGPD compliance for data handling
            - Update your Lokus configuration to allow specific exceptions
            
            ### Need help?
            - 📚 Check the [Lokus documentation](https://github.com/geavenx/lokus)
            - 🔧 Review your \`.forbidden_keys.yaml\` configuration
            - 🛡️ Ensure your API follows OWASP API Security guidelines
            
            ---
            *This check was performed by [Lokus](https://github.com/geavenx/lokus) - API Security & LGPD Compliance Validator*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: Skip validation comment
        if: steps.check-changes.outputs.changes == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            const comment = `## 🔒 Lokus API Security Validation - ⏭️ SKIPPED
            
            No API specification changes detected in this PR.
            
            **Files checked for changes:**
            - \`*.yaml\`
            - \`*.yml\`
            - \`*.json\`
            
            ---
            *This check was performed by [Lokus](https://github.com/geavenx/lokus) - API Security & LGPD Compliance Validator*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: Fail job if validation failed
        if: steps.check-changes.outputs.changes == 'true' && steps.lokus-validation.outputs.validation == 'failure'
        run: |
          echo "❌ Lokus validation failed. Please fix the issues above."
          exit 1