# Strict Security Configuration
# This configuration provides comprehensive security checks for production environments

forbidden_keys:
  # Authentication and authorization related
  - "apiKey"
  - "password"
  - "secretKey"
  - "token"
  - "secret"
  - "key"
  - "auth"
  - "credential"
  - "pass"
  - "pwd"
  - "access_token"
  - "refresh_token"
  - "bearer_token"
  - "jwt"
  - "session"
  - "cookie"
  
  # Infrastructure and configuration
  - "database"
  - "db_password"
  - "connection_string"
  - "api_secret"
  - "private_key"
  - "client_secret"
  - "app_secret"
  
  # Common sensitive information
  - "email"
  - "phone"
  - "ssn"
  - "cpf"
  - "cnpj"
  - "credit_card"
  - "card_number"
  - "account_number"

forbidden_key_patterns:
  # Token patterns
  - ".*_token$"
  - ".*_key$"
  - ".*_secret$"
  - ".*_password$"
  - ".*_pass$"
  - ".*_pwd$"
  
  # Secret patterns
  - "^secret_.*"
  - "^api_.*_secret$"
  - "^auth_.*"
  - "^credential_.*"
  - ".*_credential$"
  - ".*_auth$"
  
  # Sensitive data patterns
  - ".*_email$"
  - ".*_phone$"
  - ".*_ssn$"
  - ".*_cpf$"
  - ".*_cnpj$"
  - ".*_card.*"
  - ".*_account.*"
  
  # Infrastructure patterns
  - ".*_url$"
  - ".*_host$"
  - ".*_port$"
  - ".*_database$"
  - ".*_db$"
  - ".*_connection.*"

forbidden_keys_at_paths:
  # Info section restrictions
  - path: "info.contact.email"
    key: "email"
    reason: "Contact email should not be exposed in API specification"
  
  - path: "info.license.url"
    key: "url"
    reason: "License URL should be generic, not internal"
  
  # Server section restrictions
  - path: "servers"
    key: "url"
    reason: "Server URLs should not contain sensitive information or internal addresses"
  
  # Security schemes restrictions
  - path: "components.securitySchemes"
    key: "apiKey"
    reason: "API key values should not be embedded in specification"
  
  - path: "components.securitySchemes"
    key: "bearerFormat"
    reason: "Bearer token format should not reveal sensitive details"
  
  # Examples restrictions
  - path: "components.examples"
    key: "value"
    reason: "Examples should not contain real sensitive data"
  
  # Schema restrictions
  - path: "components.schemas"
    key: "example"
    reason: "Schema examples should not contain real sensitive data"

allowed_exceptions:
  # Allow specific cases where security-related terms are legitimate
  - key: "security"
    path_prefix: "components.schemas"
    reason: "Security-related schema definitions are allowed"
  
  - key: "auth"
    path_prefix: "paths"
    reason: "Authentication endpoints are allowed in paths"
  
  - key: "token"
    path_prefix: "components.schemas.TokenResponse"
    reason: "Token response schema is allowed"