name: Swagger/OpenAPI Validator CI

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/swagger_validator.yml"
      - "**.md"
      - "**.py"
      - "**.yaml"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/swagger_validator.yml"
      - "**.md"
      - "**.py"
      - "**.yaml"

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.4"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        run: uv python install # This will respect the Python version pinned in the project

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run pytest tests

      - name: Run Swagger Validator on clean dummy file (expect success)
        run: |
          uv run swagger_validator sample_clean_spec.yaml
        # This step should pass (exit code 0)
